api_platform:
  defaults:
    pagination_items_per_page: 5
  oauth:
    # To enable or disable oauth.
    enabled: true

    # The oauth client id.
    clientId: '123'

    # The oauth client secret.
    clientSecret: '123'

    # The oauth type.
    type: 'oauth2'

    # The oauth flow grant type.
    flow: 'password'

    # The oauth token url.
    tokenUrl: '/token'

    # The oauth authentication url.
    authorizationUrl: '/authorize'

    # The oauth scopes.
    scopes: []
