api_platform:
  defaults:
    pagination_items_per_page: 5
  oauth:
    # To enable or disable oauth.
    enabled: true

    # The oauth client id.
    clientId: '123'

    # The oauth client secret.
    clientSecret: '123'

    # The oauth type.
    type: 'oauth2'

    # The oauth flow grant type.
    flow: 'password'

    # The oauth token url.
    tokenUrl: '/token'

    # The oauth authentication url.
    authorizationUrl: '/authorize'

    # The oauth scopes.
    scopes: []
  formats:
    json:
      mime_types: [ 'application/json' ]

    jsonld:
      mime_types: [ 'application/ld+json' ]

    html:
      mime_types: [ 'text/html' ]

    formData:
      mime_types: [ 'multipart/form-data' ]

#    # The list of enabled patch formats. The first one will be the default.
#    patch_formats:
#      json:
#        mime_types: [ 'application/json' ]
#
#    # The list of enabled error formats. The first one will be the default.
#    error_formats:
#      jsonproblem:
#        mime_types: [ 'application/problem+json' ]
#
#      jsonld:
#        mime_types: [ 'application/ld+json' ]
#
#      # ...
